# KV namespace configuration
kv_namespaces = [
  { binding = "KV", preview_id="546f0391fc3a419f94246592b5323420", id = "01ec1097f60f48bbb480bdd623251d37" }
]

# Run the `npx wrangler d1 create sonicjs` command and copy the id below to the database_id field
[[d1_databases]]
binding = "D1"
database_name = "heyagent-cms-db"
database_id = "cb7f1dc4-0a0a-403f-9b0a-304afb40b466"

[[r2_buckets]]
binding = "R2"
bucket_name = "sonicjs"

[vars]
#auth settings
INVALIDATE_USER_SESSIONS = false
REQUIRE_EMAIL_CONFIRMATION = true
USERS_CAN_REGISTER = true

# password reset settings
RESET_PASSWORD_EXPIRATION_TIME = 1200000          # 20 minutes in milliseconds
PASSWORD_RESET_EMAIL_SUBJECT="SonicJS Password Reset"

# cache
DISABLED_CACHE = true

# reset email service
RESEND_API_KEY = "re_DtjnPQRe_JtRPG2WM6aipGQLLXa4rKX8c"

#email settings
EMAIL_ENABLED = true
EMAIL_FROM="me@example.com"
EMAIL_BASE_URL="https://example.com"
EMAIL_FROM_NAME="Example"
EMAIL_SEND_WELCOME_EMAIL = true

# one time password settings
ONE_TIME_PASSWORD_CHARACTER_LENGTH = 5
ONE_TIME_PASSWORD_EXPIRATION_TIME = 1200000 # 20 minutes in milliseconds
ONE_TIME_PASSWORD_EMAIL_SUBJECT="Your SonicJS OTP"

#email confirmation settings
EMAIL_CONFIRMATION_SUBJECT = "Your SonicJS Email Confirmation"
EMAIL_CONFIRMATION_REDIRECT_URL = "https://sonicjs.com/login" # after user clicks confirmation link, they will be redirected to this url
AUTO_LOGIN_AFTER_EMAIL_CONFIRMATION = true

# testing
TESTING_MODE = true # do not set to true in production, it enables e2e endpoints
